package scanner

type MODE_TYPE string

const (
	GORM_MODE MODE_TYPE = "gorm"
	RMQ_MODE  MODE_TYPE = "rmq"
)

type LOG_STATE int

const (
	LOG_STATE_PENDING   LOG_STATE = 0
	LOG_STATE_PROCESSED LOG_STATE = 1
	LOG_STATE_CHECKED   LOG_STATE = 2
)

type CHECK_STATE int

const (
	CHECK_STATE_PENDING CHECK_STATE = 0
	CHECK_STATE_CHECKED CHECK_STATE = 1
)
