logger:
  level : "info"
  stdout: true
# e-scanner.mode = gorm需要配置数据库连接
database:
  default:
    #ink:  "mysql:root:1qaz2wsx@tcp(192.168.100.1:3306)/test"
    link:  "pgsql:root:root@tcp(192.168.100.1:5432)/postgres"
    #link:  "sqlite::@file(test.db)"
    debug: "true"
    
# e-scanner.mode = rmq需要配置mq连接
# mq:
#   type: rokcetmq
#   endpoint: 192.168.100.1:8081
#   defaultTopic: test1
#   defaultGroupName: ConsumerGroup1

contracts:
    address:
      nftManager: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9

e-scanner:
  mode: gorm  #可选[gorm,rmq]
  rpc: http://127.0.0.1:8545
  contracts:
    - name: NFTMint  #扫描器名称(控制在10字符内)
      check: true
      address: ["0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"] #合约地址
      topics: 
        - ["Mint(address,address,uint256,uint256,uint256)"] #监听事件
    
      


