// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ethscanner/ethereum-log-scanner/internal/dao/internal"
)

// internalDesertNftMintRecordsDao is internal type for wrapping internal DAO implements.
type internalDesertNftMintRecordsDao = *internal.DesertNftMintRecordsDao

// desertNftMintRecordsDao is the data access object for table desert_nft_mint_records.
// You can define custom methods on it to extend its functionality as you wish.
type desertNftMintRecordsDao struct {
	internalDesertNftMintRecordsDao
}

var (
	// DesertNftMintRecords is globally public accessible object for table desert_nft_mint_records operations.
	DesertNftMintRecords = desertNftMintRecordsDao{
		internal.NewDesertNftMintRecordsDao(),
	}
)

// Fill with you ideas below.
