// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ethscanner/ethereum-log-scanner/internal/dao/internal"
)

// internalHdContractEventDao is internal type for wrapping internal DAO implements.
type internalHdContractEventDao = *internal.HdContractEventDao

// hdContractEventDao is the data access object for table hd_contract_event.
// You can define custom methods on it to extend its functionality as you wish.
type hdContractEventDao struct {
	internalHdContractEventDao
}

var (
	// HdContractEvent is globally public accessible object for table hd_contract_event operations.
	HdContractEvent = hdContractEventDao{
		internal.NewHdContractEventDao(),
	}
)

// Fill with you ideas below.
