// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ethscanner/ethereum-log-scanner/internal/dao/internal"
)

// internalHdSystemConfigDao is internal type for wrapping internal DAO implements.
type internalHdSystemConfigDao = *internal.HdSystemConfigDao

// hdSystemConfigDao is the data access object for table hd_system_config.
// You can define custom methods on it to extend its functionality as you wish.
type hdSystemConfigDao struct {
	internalHdSystemConfigDao
}

var (
	// HdSystemConfig is globally public accessible object for table hd_system_config operations.
	HdSystemConfig = hdSystemConfigDao{
		internal.NewHdSystemConfigDao(),
	}
)

// Fill with you ideas below.
